services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: quinie
      MYSQL_USER: quinie
      MYSQL_PASSWORD: quinie
      MYSQL_ROOT_PASSWORD: rootquinie
    ports:
      - "3306:3306"
    volumes:
      - quinie_mysql:/var/lib/mysql
volumes:
  quinie_mysql:
